# Generated by Django 2.1.5 on 2019-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=13)),
                ('size', models.CharField(max_length=9)),
                ('slug', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='image.svg', upload_to='')),
            ],
        ),
    ]
