# Generated by Django 2.1.5 on 2019-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgUploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, default='jeep.png', upload_to=''),
        ),
    ]
